name: Sonar (fork PRs)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read            # do not grant write; scanner doesn't need it
  pull-requests: write      # only if you want PR decorations/comments; otherwise remove

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the *base* repo at the base commit (workflow comes from here, not the fork)
      - name: Checkout base repo (for workflow only)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0

      # 2) Checkout the PR HEAD from the fork into a subfolder **as data**.
      #    This avoids running any workflow code from the fork.
      - name: Checkout PR HEAD (read-only)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
          fetch-depth: 0

      # (Optional) quick sanity/debug — remove later
      - name: Debug inputs
        run: |
          echo "PR #: ${{ github.event.pull_request.number }}"
          echo "PR head: ${{ github.event.pull_request.head.ref }} @ ${{ github.event.pull_request.head.sha }}"
          echo "PR base: ${{ github.event.pull_request.base.ref }} @ ${{ github.event.pull_request.base.sha }}"
          ls -la pr || true
          git -C pr rev-parse --short HEAD

      # 3) Run the Sonar scanner against the PR code.
      #    Point projectBaseDir to where the code lives inside the repo (e.g., pr/caldera).
      - name: SonarQube Scan (fork PR)
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        # repo/org secret
          # If self-hosted SonarQube (not SonarCloud), also set:
          # SONAR_HOST_URL: https://sonar.example.com
        with:
          args: >
            -Dsonar.projectBaseDir=pr/caldera
            # If not in properties file, pass these explicitly:
            # -Dsonar.projectKey=<your-project-key>
            # -Dsonar.organization=<your-org>            # SonarCloud only
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
